import { carrierMatches, filterWeapons, brSummary, formatValue } from './logic.js';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,carrierMap=new Map(),filtered=[],page=1,category='',pageSize=20;
const ids=['origin','country','aircraft','mode','min','max','guidance','fox','mounted','variants','field','operator','value','search'];
const state=()=>Object.fromEntries([...ids.map(id=>[id,$(id).value]),['category',category]]);
const categoryLabels={'AAM - air-to-air':'Air-to-air','ARM - anti-radiation':'Anti-radiation','ASM - anti-ship / surface ARH':'Anti-ship','AGM - electro-optical':'AGM · EO','AGM - laser guided':'AGM · Laser','ATGM - laser guided':'ATGM · Laser','ATGM - beam riding':'Beam riding','ATGM - SACLOS / MCLOS':'SACLOS / MCLOS'};
function options(id,values){const el=$(id);for(const value of [...new Set(values.filter(v=>v!=null&&v!==''))].sort((a,b)=>typeof a==='number'?a-b:String(a).localeCompare(String(b))))el.add(new Option(id==='country'?({Usa:'USA',Ussr:'USSR'}[value]||value):value,value));}
function matchingCarriers(w,s){return (carrierMap.get(w.File)||[]).filter(c=>carrierMatches(c,s));}
function drawCategories(){const categories=['',...Object.keys(categoryLabels)];$('categories').innerHTML=categories.map(c=>`<button data-category="${esc(c)}" class="${category===c?'active':''}" aria-pressed="${category===c}">${esc(categoryLabels[c]||'All weapons')}<span>${c?data.weapons.filter(w=>w.Category===c).length:data.weapons.length}</span></button>`).join('');}
function update(resetPage=true){if(!data)return;if(resetPage)page=1;const s=state();filtered=filterWeapons(data.weapons,carrierMap,s);const [sort,direction]=$('sort').value.split('|');filtered.sort((a,b)=>{const av=sort==='br'?brSummary(carrierMap.get(a.File)||[],s.mode).median:a[sort],bv=sort==='br'?brSummary(carrierMap.get(b.File)||[],s.mode).median:b[sort];if(av==null&&bv==null)return a.File.localeCompare(b.File);if(av==null)return 1;if(bv==null)return -1;const result=typeof av==='number'?av-bv:String(av).localeCompare(String(bv),undefined,{numeric:true});return (direction==='desc'?-result:result)||a.File.localeCompare(b.File);});
const links=filtered.flatMap(w=>matchingCarriers(w,s)),br=brSummary(links,s.mode);$('weaponCount').textContent=filtered.length;$('totalLabel').textContent=`of ${data.weapons.length} dataset entries`;$('originCount').textContent=new Set(filtered.map(w=>w.Nation)).size;$('carrierCount').textContent=new Set(links.map(c=>c['Aircraft ID'])).size;$('brSpan').textContent=br.min==null?'—':`${br.min.toFixed(1)}–${br.max.toFixed(1)}`;$('modeLabel').textContent=$('mode').selectedOptions[0].text;$('resultCount').textContent=filtered.length;$('valueLabel').hidden=['present','missing'].includes(s.operator);drawCategories();drawChips();renderRows();}
function drawChips(){const labels={origin:'Origin',country:'Carrier country',aircraft:'Aircraft',min:'Min BR',max:'Max BR',guidance:'Guidance',fox:'Fox',mounted:'Aircraft reference',variants:'Variant',field:'Specification',value:'Value',search:'Search'};const s=state();$('activeFilters').innerHTML=Object.entries(labels).filter(([k])=>s[k]).map(([k,v])=>`<button data-clear="${k}" aria-label="Remove ${esc(v)} filter">${v}: ${esc(s[k])} ×</button>`).join('')+(category?`<button data-clear="category">${esc(categoryLabels[category])} ×</button>`:'');}
function renderRows(){const s=state();page=Math.min(page,Math.max(1,Math.ceil(filtered.length/pageSize)));const start=(page-1)*pageSize;
$('rows').innerHTML=filtered.slice(start,start+pageSize).map(w=>{const carriers=carrierMap.get(w.File)||[],br=brSummary(carriers,s.mode);return `<tr><td><button class="weapon-name" data-detail="${esc(w.File)}">${esc(w.Weapon)}</button>${w['Fox Class']?`<span class="pill">${esc(w['Fox Class'])}</span>`:''}<span class="subline">${esc(w['Guidance Family'])}</span>${w['Is Variant']==='Yes'?`<span class="subline">Variant · ${esc(w.File)}</span>`:''}</td><td>${esc(w.Nation)}</td><td><span class="br-value">${br.median==null?'—':formatValue(br.median)}</span><span class="subline">${br.min==null?'No known BR':`${br.min.toFixed(1)}–${br.max.toFixed(1)}`}</span></td><td>${formatValue(w['Hard Max Range (km)'])}${w['Hard Max Range (km)']!=null?' km':''}</td><td>${formatValue(w['Max Overload (G)'])}${w['Max Overload (G)']!=null?' G':''}</td><td>${carriers.length}<span class="subline">${matchingCarriers(w,s).length} matching</span></td><td><button data-detail="${esc(w.File)}" aria-label="View ${esc(w.Weapon)} details">↗</button></td></tr>`;}).join('');$('empty').hidden=filtered.length!==0;$('pageInfo').textContent=filtered.length?`${start+1}–${Math.min(start+pageSize,filtered.length)} of ${filtered.length} weapons · Page ${page}`:'0 weapons';$('prev').disabled=page<=1;$('next').disabled=page*pageSize>=filtered.length;}
function reset(){for(const id of ids)$(id).value=id==='mode'?'BR Realistic':id==='operator'?'contains':'';category='';update();}
function table(rows,columns){return `<div class="table-scroll"><table><thead><tr>${columns.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${esc(typeof r[c]==='number'?formatValue(r[c]):r[c]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function showDetail(file){const w=data.weapons.find(w=>w.File===file);if(!w)return;const carriers=carrierMap.get(file)||[],s=state(),matches=matchingCarriers(w,s),base=file.replace(/\.blkx$/,'');const envelopes=data.envelopes.filter(r=>r.Weapon.endsWith(`[${base}]`));$('detailTitle').textContent=w.Weapon;$('detailCategory').textContent=`${w.Category} / ${w.Nation}`;
$('detailBody').innerHTML=`<p class="helper">${esc(w['Full Name'])} · ${esc(w.File)}</p><div class="detail-summary">${[['Guidance',w['Fox Class']||w['Guidance Family']],['Launch mass',w['Launch Mass (kg)']==null?'—':formatValue(w['Launch Mass (kg)'])+' kg'],['Hard max range',w['Hard Max Range (km)']==null?'—':formatValue(w['Hard Max Range (km)'])+' km'],['Carrier aircraft',carriers.length]].map(([k,v])=>`<div><span>${k}</span><strong>${esc(v)}</strong></div>`).join('')}</div><details class="specs" open><summary>Carrier aircraft (${carriers.length}) · ${matches.length} match your filters</summary><div><p class="helper">BR belongs to the aircraft. All carrier links appear below, including those outside your current filters.</p>${carriers.length?table(carriers,['Aircraft','Aircraft Nation','Aircraft Rank','BR Arcade','BR Realistic','BR Simulator','BR Ground RB','Unit Class']):'<p>No aircraft reference found in this dataset. This does not establish a ground-launch capability.</p>'}</div></details><details class="specs"><summary>Launch envelope (${envelopes.length} records)</summary><div><p class="helper">Stored AAM launch cases at specific altitudes and speeds. Hard max range is a separate cut-off. Case numbers retain the source labels.</p>${envelopes.length?table(envelopes,Object.keys(envelopes[0]).filter(k=>k!=='Weapon')):'<p>No launch-envelope records for this exact weapon file.</p>'}</div></details><details class="specs" open><summary>All specifications · ${Object.keys(w).length} fields</summary><div><input type="search" id="specSearch" class="detail-search" aria-label="Find a specification" placeholder="Find a specification, e.g. radar, IRCCM, warhead…"><dl class="spec-grid">${Object.entries(w).map(([k,v])=>`<div class="spec-item" data-spec="${esc((k+' '+(data.dictionary[k]||'')).toLowerCase())}"><dt title="${esc(data.dictionary[k]||'')}">${esc(k)}</dt><dd>${esc(typeof v==='number'?formatValue(v):v??'—')}</dd>${data.dictionary[k]?`<p class="helper" style="margin:6px 0 0">${esc(data.dictionary[k])}</p>`:''}</div>`).join('')}</dl></div></details>`;
$('specSearch').addEventListener('input',e=>document.querySelectorAll('[data-spec]').forEach(el=>el.hidden=!el.dataset.spec.includes(e.target.value.toLowerCase())));$('detail').showModal();$('detail').scrollTop=0;}
$('mobileFilters').onclick=()=>{const open=document.body.classList.toggle('filters-open');$('mobileFilters').setAttribute('aria-expanded',String(open));$('mobileFilters').textContent=open?'Hide filters':'Show filters';};
$('closeDetail').onclick=()=>$('detail').close();$('closeSource').onclick=()=>$('source').close();for(const id of ['detail','source'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$(id).close();}});
$('sourceBtn').onclick=()=>{if(!data)return;$('sourceBody').innerHTML=`<p>Source workbook: ${esc(data.meta.sourceWorkbook)}<br>Snapshot: ${esc(data.meta.snapshot)}</p><p><a href="${esc(data.meta.sourceRepository)}" target="_blank" rel="noopener noreferrer">War-Thunder-Datamine repository ↗</a></p><p>This app uses the supplied snapshot. It does not update live.</p>${data.readme.map(([a,b])=>b!=null?`<p><strong>${esc(a)}</strong><br>${esc(b)}</p>`:`<h3>${esc(a)}</h3>`).join('')}`;$('source').showModal();};
for(const id of ids)$(id).addEventListener(['search','aircraft','value'].includes(id)?'input':'change',()=>update());$('sort').onchange=()=>update();$('reset').onclick=reset;$('emptyReset').onclick=reset;$('prev').onclick=()=>{page--;renderRows();};$('next').onclick=()=>{page++;renderRows();};$('categories').onclick=e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;update();}};$('activeFilters').onclick=e=>{const b=e.target.closest('[data-clear]');if(!b)return;const k=b.dataset.clear;if(k==='category')category='';else $(k).value='';if(k==='field')$('value').value='';update();};$('rows').onclick=e=>{const b=e.target.closest('[data-detail]');if(b)showDetail(b.dataset.detail);};document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('search').focus();}});
try{data=globalThis.__WEAPONS_DATA__;if(!data?.weapons?.length)throw Error('Embedded dataset is unavailable');for(const c of data.carriers){if(!carrierMap.has(c.File))carrierMap.set(c.File,[]);carrierMap.get(c.File).push(c);}document.querySelector('.snapshot strong').textContent=data.meta.snapshot||'Unknown';options('origin',data.weapons.map(w=>w.Nation));options('country',data.carriers.map(c=>c['Aircraft Nation']));options('guidance',data.weapons.map(w=>w['Guidance Family']));options('field',Object.keys(data.weapons[0]));const brs=data.carriers.flatMap(c=>['BR Realistic','BR Arcade','BR Simulator','BR Ground RB'].map(k=>c[k]));options('min',brs);options('max',brs);update();}catch(error){console.error(error);$('loadError').hidden=false;$('pageInfo').textContent='Dataset unavailable';$('totalLabel').textContent='Dataset unavailable';}
