import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {filterWeapons,brSummary} from '../logic.js';
const d=JSON.parse(fs.readFileSync(new URL('../data/weapons.json',import.meta.url)));const map=new Map();for(const c of d.carriers){if(!map.has(c.File))map.set(c.File,[]);map.get(c.File).push(c);}
const ground=JSON.parse(fs.readFileSync(new URL('../data/ground.json',import.meta.url)));
const infantry=JSON.parse(fs.readFileSync(new URL('../data/infantry.json',import.meta.url)));
const s={search:'',origin:'',country:'',aircraft:'',mode:'BR Realistic',min:'',max:'',guidance:'',fox:'',mounted:'',variants:'',field:'',operator:'contains',value:'',category:''};
test('All master entries are retained, without duplicating category sheets',()=>{assert.equal(d.weapons.length,432);assert.equal(new Set(d.weapons.map(w=>w.File)).size,432);assert.equal(d.carriers.length,2281);assert.equal(d.envelopes.length,3044);assert.equal(filterWeapons(d.weapons,map,s).length,432);for(const c of d.carriers)assert.ok(d.weapons.some(w=>w.File===c.File));});
test('Country, aircraft and BR must match the same carrier',()=>{const w={File:'x'},m=new Map([['x',[{'Aircraft Nation':'USA',Aircraft:'A','Aircraft ID':'a','BR Realistic':10},{'Aircraft Nation':'France',Aircraft:'B','Aircraft ID':'b','BR Realistic':12}]]]);assert.equal(filterWeapons([w],m,{...s,country:'USA',min:'12'}).length,0);assert.equal(filterWeapons([w],m,{...s,country:'USA',aircraft:'B'}).length,0);assert.equal(filterWeapons([w],m,{...s,country:'France',min:'12',max:'12'}).length,1);});
test('Missing BR does not become zero, and median ignores missing values',()=>{assert.deepEqual(brSummary([{'BR Realistic':null},{'BR Realistic':10},{'BR Realistic':11}],'BR Realistic'),{min:10,max:11,median:10.5});assert.equal(filterWeapons(d.weapons,map,{...s,min:'14',max:'1'}).length,0);});
test('Advanced specification filter preserves missing versus zero',()=>{const w=[{File:'a',n:0},{File:'b',n:null},{File:'c',n:5}];assert.deepEqual(filterWeapons(w,new Map(),{...s,field:'n',operator:'lte',value:'0'}).map(x=>x.File),['a']);assert.deepEqual(filterWeapons(w,new Map(),{...s,field:'n',operator:'missing'}).map(x=>x.File),['b']);});
test('Every returned real-data carrier filter has supporting evidence',()=>{const f={...s,country:'Usa',min:'10',max:'12'};const result=filterWeapons(d.weapons,map,f);assert.ok(result.length>0);for(const w of result)assert.ok(map.get(w.File).some(c=>c['Aircraft Nation']==='Usa'&&c['BR Realistic']>=10&&c['BR Realistic']<=12));});
test('Ground records and every relationship join to a known vehicle',()=>{assert.equal(ground.vehicles.length,1237);const ids=new Set(ground.vehicles.map(row=>row['Vehicle ID']));for(const collection of [ground.loadoutGuide,ground.loadoutDetail,ground.vehicleGuns,ground.vehicleAmmo])for(const row of collection)assert.ok(ids.has(row['Vehicle ID']));});
test('Infantry records and every relationship join to a known weapon',()=>{assert.equal(infantry.weapons.length,81);const names=new Set(infantry.weapons.map(row=>row.Weapon));for(const collection of [infantry.weaponCartridges,infantry.weaponMagazines])for(const row of collection)assert.ok(names.has(row.Weapon));});
